### ISSUE TITLE
Mac Server - Ctrl and Meta swaped when trying to set Hotkeys

### ISSUE THREAD

**Issue by AmigaAbattoir** [deskflow/deskflow#7972]
### Project

Deskflow

### Deskflow version number

1.17.2.0 (9084a490)

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.2

### Deskflow configuration

macOS 15.2 server (right), macOS 15.2 client left, Windows 10 client left most

### What steps will reproduce the problem?

1. Start Deskflow
2. On server, click Configure
3. Select Hotkeys tab
4. Either make a New one, or edit an existing one.
5. Click for the keystroke()
6. Enter combination of with the control key or cmd (meta) key

Expected results:
1. If pressing the control key, the "Control" key shows up in the keystroke()
2. If pressing the cmd key, the "Meta" key shows up in the keystroke()

Actual results:
1. Pressing the control key shows "Meta" in the keystroke
2. Pressing the cmd key shows "Control" in the keystroke 

### Additional information

I was trying to configure 2 hotkeys, and couldn't figure out why they were not working. Then I realized that they are getting the wrong keys for cmd and ctrl. So in order to make something like ctrl+shift+home work, I had to enter cmd+shift+home.

This was even before adding the Windows 10 machine, which on the computer setting, only "Super" and "Ctrl" were swapped. And hitting the actual ctrl+shift+home worked properly on that.

**Comment by nbolton** [comment]
Thanks for reporting this bug. We will try to reproduce this when we can.

**Comment by nbolton** [comment]
@sithlord48 You removed 'triage' label. Does this mean you were able to repro the bug?

**Comment by sithlord48** [comment]
No i looked at It,  I can not reproduce this on my setup meta is command for me.

**Comment by sithlord48** [comment]
Could be fixed by: #8046 ?

**Comment by AmigaAbattoir** [comment]
Tried to check with the continuous build from today [8533348](https://github.com/deskflow/deskflow/commit/8533348c885138cac80fd98fbf9c1435f1da5387) which showed up as V1.18.0.49 and I still have the same issue, and on top of that now I cannot type at all on the other computers. The keystrokes still register with the server's window, and doesn't transfer at all to the other computers.

**Comment by AmigaAbattoir** [comment]
I did. I removed the accessibility items, deleted Deskflow and restarted. Unzipped the continuous build file, started it up, got the prompt for allowing the accessibility items. I enabled it and started Deskflow again.

If I was in TextEdit on the server's screen, and then I tried going to another computer, and I could open a browser, click in the URL bar and then try typing, it would end up typing in  TextEdit on the server.

**Comment by AmigaAbattoir** [comment]
Deskflow: 1.20.0.0 (3ef5793b)
Qt: 6.8.2
System: macOS Sequoia (15.3)

It still happens. And I cannot get any hotkey combinations to do anything. Just so I know, if I do a hotkey combination would this show up in the log area?

**Comment by gus-costa** [comment]
I have the same issue. 

Deskflow: 1.20.1.0 (bc96ddeb)
Qt: 6.8.2
System: macOS Sequoia (15.3)

**Comment by sithlord48** [comment]
Have you tried to remap them on the screen settings ?

**Comment by AmigaAbattoir** [comment]
If I go in to **Configuration**, then double click on my Windows client, **Modifier Keys** have been remapped to **Ctrl -> Super** / **Super -> Ctrl** this way the Mac cmd key is remapped to Ctrl on Windows. All the others (Mac server, 2 Mac clients) do not have any computer settings changed.
